# Generated by Django 4.2.3 on 2024-06-21 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp1.paragraph')),
            ],
        ),
    ]
